version: '2'

volumes:
  data:
    driver: local

services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'issuer'
      POSTGRES_PASSWORD: 'secretpassword'
      POSTGRES_DB: 'issuerdb'
